services:
  postgres:
    image: postgres:latest
    container_name: postgres-container
    environment:
      POSTGRES_USER: vitalii
      POSTGRES_PASSWORD: 260604
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    restart: always